name: Cypress # NB: The name is used in workflow_run

on:
  push:
    branches: [main, beta, chore/*, fix/*, feat/*]
  pull_request:
    types: [opened]
    branches: [main, beta]

jobs:
  build:
    name: Cypress tests

    strategy:
      matrix:
        platform: [ubuntu-latest] # other OSes are not needed at the moment [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    env:
      CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Use deps cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ./.yarn/cache
          key: deps-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Use Gatsby cache
        uses: actions/cache@v3
        id: gatsby-cache
        with:
          path: |
            ./example-basic/.cache
            ./example-basic/public
          key: gatsby-${{ runner.os }}

      - name: Use Cypress cache
        uses: actions/cache@v3
        id: cypress-binary-cache
        with:
          path: ~/.cache/Cypress
          key: cypress-binary-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install deps
        run: yarn install --immutable

      - name: Install Cypress
        if: steps.cypress-binary-cache.outputs.cache-hit != 'true'
        run: yarn workspace integration-tests cypress install

      - name: Use Cypress
        uses: cypress-io/github-action@v5
        with:
          install: false
          working-directory: integration-tests
          command: yarn test:cypress:ci
