name: GitHub Pages

on:
  workflow_run:
    workflows: ['Cypress']
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    name: GitHub Pages

    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Use deps cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ./.yarn/cache
          key: deps-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Use Gatsby cache
        uses: actions/cache@v3
        id: gatsby-cache
        with:
          path: |
            ./example-basic/.cache
            ./example-basic/public
          key: gatsby-gh-pages-${{ runner.os }}

      - name: Install deps
        run: yarn install --immutable

      - name: Build example-basic
        run: yarn workspace example-basic gatsby build --prefix-paths

      - name: Deploy example-basic
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example-basic/public
